### ISSUE TITLE
Buy tiny speaker: bone conduction or other

### ISSUE THREAD

**Issue by pkarnati2004** [pkarnati2004/ppat-project#12]

**Comment by korrawat** [comment]
Options
- Adafruit's [Bone conduction speaker](https://www.adafruit.com/product/1674)
  - Currently out of stock, but available on other websites.
  - > If you plan to use the bone conduction transducer for prolonged direct contact with skin, we recommend that cover the transducer and wire connections with something like Sugru to prevent accidental shorting of driver current through the skin, due to sweat and electrolyte accumulation around the metal parts.
  - Instructions [here](https://learn.adafruit.com/piglass-wearable-raspberry-pi-computer?view=all#bone-conduction-transducer)
- [Speaker pHAT](https://shop.pimoroni.com/products/speaker-phat)
  - Increases total thickness; might be a concern. See this [YouTube example](https://www.youtube.com/watch?v=fPUUb3abEVU).
- Another [speaker pHAT](https://www.raspiaudio.com/audioamp)
  - Easier to assemble (no soldering), but larger 
- Adafruit's [Mini metal speaker](https://www.adafruit.com/product/1890)

According to [PiGlass tutorial](https://learn.adafruit.com/piglass-wearable-raspberry-pi-computer?view=all), I bought the following:
- [Pimoroni pHAT DAC for Raspberry Pi Zero](https://www.adafruit.com/product/3016)
- [Adafruit Mono 2.5W Class D Audio Amplifier - PAM8302](https://www.adafruit.com/product/2130)
- [Bone Conductor Transducer with Wires - 8 Ohm 1 Watt](https://www.adafruit.com/product/1674), but from [arrow.com](https://www.arrow.com/en/products/1674/adafruit-industries)

**Comment by korrawat** [comment]
maybe this instead?
https://aftershokz.com/collections/wired/products/sportz-titanium
